trigger:
- main
- development
- feature*

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: buildApp
        displayName: Build Application
        steps:
          - powershell: | 
              Write-Host "Build application step"
            displayName: Run Build Application Script

  - stage: Promotion
    jobs:
      - job: promotion
        displayName: Release Promotion
        steps:
          - checkout: self
            persistCredentials: true
          - powershell: | 
              Write-Host "Promote release to github"
              git checkout $(Build.SourceBranchName)
              
              git remote -v
              git remote remove origin
              git config http.$(ghUser).extraheader "AUTHORIZATION: bearer $(ghPassword)"
              git remote add origin2 https://github.com/NateDuff/Demo.git
              git push -u origin2 --mirror https://github.com/NateDuff/Demo.git master
