resources:
  repositories:
  - repository: Demo
    type: git
    name: Demo
  - repository: Demo
    type: github
    endpoint: MyGitHubServiceConnection
    name: NateDuff/Demo

trigger:
- main
- development
- feature*

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: buildApp
        displayName: Build Application
        steps:
          - powershell: | 
              Write-Host "Build application step"
            displayName: Run Build Application Script

  - stage: Promotion
    jobs:
      - job: promotion
        displayName: Release Promotion
        steps:
          - checkout: self
            persistCredentials: true
            path: s/demo
          - checkout: Demo
            persistCredentials: true
            path: s/demo2
          - powershell: | 
              Write-Host "Stage promotion"
              CD demo
              git checkout $(Build.SourceBranchName)

              Copy-Item -Path . -Destination ../demo2 -Exclude .git/ -Recurse -Force -Verbose
              
              Write-Host "Promote new code to github"
              CD ../demo2

              git add -A
              
              git commit -m "Publishing from Azure DevOps Git"
              
              git push -u origin main
