resources:
  repositories:
  - repository: Demo
    type: git
    name: Demo
  - repository: Demo
    type: github
    endpoint: MyGitHubServiceConnection
    name: NateDuff/Demo

trigger:
- main
- development
- feature*

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: buildApp
        displayName: Build Application
        steps:
          - powershell: | 
              Write-Host "Build application step"
            displayName: Run Build Application Script

  - stage: Promotion
    jobs:
      - job: promotion
        displayName: Release Promotion
        steps:
          - checkout: self
            persistCredentials: true
            path: s/demo
          - checkout: Demo
            persistCredentials: true
            path: s/demo2
          - powershell: | 
              Write-Host "Stage promotion"
              CD ../s/demo2
              
              ## First time only
              #git init

              CD ../demo
              git checkout $(Build.SourceBranchName)

              DIR | ? {$_.Name -notlike ".git*"} | Copy-Item -Destination ../demo2 -Recurse -Force -Verbose
              
              Write-Host "Promote new code to github"
              CD ../demo2

              git config user.name NateDuff
              git config user.email $(ghUser)
              git config http.$(ghUser).extraheader "AUTHORIZATION: bearer $(ghPassword)"

              git checkout master
              git add -A

              git remote remove origin
              git remote set-url origin https://NateDuff@github.com/NateDuff/Demo.git

              git commit -m "Publishing from Azure DevOps Git"

              git -c http.$(ghUser).extraHeader="Authorization: bearer $(ghPassword)" push -u origin master
