resources:
  repositories:
  - repository: Demo
    type: git
    name: Demo
  - repository: Demo
    type: github
    endpoint: MyGitHubServiceConnection
    name: NateDuff/Demo

trigger:
- main
- development
- feature*

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: buildApp
        displayName: Build Application
        steps:
          - powershell: | 
              Write-Host "Build application step"
            displayName: Run Build Application Script

  - stage: Promotion
    jobs:
      - job: promotion
        displayName: Release Promotion
        steps:
          - checkout: self
            persistCredentials: true
          - checkout: Demo
            persistCredentials: true
            path: demo2
          - powershell: | 
              Write-Host "Promote release to github"
              git checkout $(Build.SourceBranchName)
              
              git remote remove origin
              git config user.name NateDuff
              git config user.email $(ghUser)
              git config http.$(ghUser).extraheader "AUTHORIZATION: bearer $(ghPassword)"

              git remote add origin git@github.com:NateDuff/Demo.git
              git -c http.$(ghUser).extraHeader="Authorization: bearer $(ghPassword)" push -u origin main
              #git@github.com:yourname/yourrepo.git
